export const EVENT_TYPES = [
  "passport.created",
  "passport.suspended",
  "passport.revoked",
  "passport.key_rotated",
  "passport.rotated",
  "task.completed",
  "task.failed",
  "task.timeout",
  "task.replayed",
  "validation.passed",
  "validation.failed",
  "validation.reversed",
  "validation.requested",
  "dispute.opened",
  "dispute.resolved",
  "dispute.escalated",
  "trust.resolved",
  "trust.confidence_low",
  "trust.spike",
  "trust.collapse",
  "trust.decayed",
  "trust.recovered",
  "cluster.instability_detected",
  "validator.drift_detected",
  "route.selected",
  "route.blocked",
  "route.rerouted",
  "route.changed",
  "route.escalated",
  "executor.selected",
  "executor.blocked",
  "quorum.escalated",
  "collusion.suspected",
  "webhook.delivery.succeeded",
  "webhook.delivery.failed",
  "trust.portability.exported",
  "trust.portability.imported",
  "economic.escrow.quoted",
  "economic.risk_priced",
  "economic.attestation.issued",
  "warroom.alerted",
  "warroom.alert.raised",
  "warroom.alert.acknowledged",
  "quarantine.enforced"
];

export function makeCloudEvent({
  id,
  type,
  source,
  subject,
  trace_id,
  data,
  time
}) {
  return {
    event_id: id,
    event_type: type,
    subject_id: subject,
    trace_id,
    created_at: time,
    specversion: "1.0",
    type,
    source,
    subject,
    id,
    time,
    datacontenttype: "application/json",
    trace_id,
    data,
    ...(data && typeof data === "object" ? data : {})
  };
}
